spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        #       native:
        #         search-locations: "file:///C://Users//USER//Documents//config"
        #         search-locations: "classpath:/config"
        git:
          uri: "https://github.com/musqat/microservice-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "C7h2zvAeTrg2E7om2kqlirSNjb0z8Mzh"

server:
  port: 8071
