services:
    accounts:
      image: "muscathan/accounts:s4"
      container_name: accounts-ms
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            memory: 700M
      networks:
        - muscathan
    loans:
      image: "muscathan/loans:s4"
      container_name: loans-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700M
      networks:
        - muscathan
    cards:
      image: "muscathan/cards:s4"
      container_name: cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700M
      networks:
        - muscathan

networks:
 muscathan:
  driver: bridge